PrimeMVC/Controllers/BookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PrimeMVC.Data;
using PrimeMVC.Models;

namespace PrimeMVC.Controllers;
//[Authorize(Roles = "Admin")]
public class BookController : Controller
{
    private readonly ApplicationDbContext _db;

    public BookController(ApplicationDbContext db)
    {
        _db = db;
    }

    public IActionResult Index()
    {
        IEnumerable<Book> objBookList = _db.Books;
        return View(objBookList);
    }

    //GET
    public IActionResult Create()
    {
        return View();
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Book obj)
    {
        if (ModelState.IsValid)
        {
            obj.BookID = 0;
            _db.Books.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        return View();
    }

    //GET
    public IActionResult Edit(int? BookID)
    {
        if (BookID == null || BookID == 0)
        {
            return NotFound();
        }
        var bookFromDb = _db.Books.Find(BookID);

        if (bookFromDb == null)
        {
            return NotFound();
        }
        return View(bookFromDb);
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Book obj)
    {
        if (ModelState.IsValid)
        {
            _db.Books.Update(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        return View(obj);
    }

    //GET
    public IActionResult Delete(int? BookID)
    {
        if (BookID == null || BookID == 0)
        {
            return NotFound();
        }

        var bookFromDb = _db.Books.Find(BookID);
        if (bookFromDb == null)
        {
            return NotFound();
        }

        return View(bookFromDb);
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteBook(int? BookID)
    {
        var obj = _db.Books.Find(BookID);
        if (obj == null)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            _db.Books.Remove(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        return View(BookID);
    }
}

PrimeMVC/Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using PrimeMVC.Models;
using System.Data;

namespace PrimeMVC.Controllers
{
    public class SignUpController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }   
    }
}

PrimeMVC/Controllers/WelcomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace PrimeMVC.Controllers
{
    public class WelcomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PrimeMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimeMVC</title>
    <link rel="stylesheet" href="~/css/StyleSheet.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Welcome" asp-action="Index">Welcome</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SignUp" asp-action="Index">SignUp</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filter" asp-action="Index">Filters</a>
                        </li>
                        <li class="nav-item" >
                            <a asp-controller="Welcome" asp-action="index" class="btn btn-danger">
                                <i class="bi bi-box-arrow-left"></i> &nbsp; Logout
                                 
                                </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-top p-3 footer text-center" style="position:absolute; bottom:0; height:fit-content; width:100%;">
        <div class="container">
                &copy; Abuhamdeh's Book Center
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>